### ISSUE TITLE
Update Gogs Homepage Logo

### ISSUE THREAD

**Issue by RamonAbudAlcala** [Kos-M/GogsThemes#12]
Hi Thanks for creating this theme. I have just installed successfully.

I noticed that the main logo in the center of Gogs homepage is now different from the one on your screenshots.
I can only guess that it was updated by Gogs, and because of that it stays as it was in the original theme. That is, the big letters "Gogs" are black on a dark grey background.

Here is a screenshot.

![image](https://user-images.githubusercontent.com/20816167/233777873-b35a283f-82ea-498d-8f1e-fc644b1926e6.png)

It doesn't look bad to me, but I thought I'd point it out.

**Comment by Kos-M** [comment]
Hello @RamonAbudAlcala !
Thanks for your input , currently not using Gogs so  didn't have the chance to noticed that.
Indeed seems  something changed in Gogs  leading theme not catching this.

There are several other small issues not covered so much by this theme , so if you notice anything else 
feel free to issue it also  :)

I 'll flag it good first issue , so if anyone can help with this , happy to merge it . 
Pull Request should include a screenshot of current change.

**Comment by Kos-M** [comment]
i checked again , 
and seems that in v 0.11.86 of gogs , they used plain text , and in later versions changed to image with this styling.
So its correct that way.
![image](https://github.com/Kos-M/GogsThemes/assets/46938390/00b73850-8dc9-42fd-afe4-f2b78ef9559b)
