### ISSUE TITLE
Work with `custom` folder

### ISSUE THREAD

**Issue by xv1t** [Kos-M/GogsThemes#2]
Worked after 
```bash
cd "gogs/custom/templates/inject";
ln -s "../../../templates/inject/head.tmpl";
```
Thanx for dark theme!

**Comment by Kos-M** [comment]
Thanks for feedback mate , 
Dìd you tried steps bellow : 
## Dark
 - ````cd $GOGS_ROOT```` 
 - ```git clone https://github.com/Kos-M/GogsThemes.git```
 - ````echo  '<link rel="stylesheet" href="/css/themes/dark_theme.css">' >> templates/inject/head.tmpl```` 
 - ```mv  ./GogsThemes/img/grad1.png public/img```
 - ```mv ./GogsThemes/themes/dark_theme.css public/css/themes```
 - ```rm -r ./GogsThemes```

... and didn't enabled Dark theme ?
$GOGS_ROOT = your gog's root directory , absolute path.
