### ISSUE TITLE
strange behavior of right aligned element

### ISSUE THREAD

**Issue by blackr4in** [Kos-M/GogsThemes#3]
`<div class="right fitted item">`
is not aligned correctly in the dark theme
![image](https://user-images.githubusercontent.com/11722315/86343388-907a3880-bc61-11ea-9d03-7487dd8f631f.png)

**Comment by blackr4in** [comment]
Solved by adding
`.repository #clone-panel {
    margin-left: 5px;
    width: auto !important;
}`

**Comment by Kos-M** [comment]
hey , file a pull request to check it and merge it to master .
