### ISSUE TITLE
Relative paths in css and template files

### ISSUE THREAD

**Issue by D-Walter** [Kos-M/GogsThemes#8]
My gogs is running in docker container and are being reverse proxied by nginx on another device.

In this situation, `/css/themes/velvet.css` in head.tmpl seems not working, which is the same as `/img/grad1.png` in css files.

For proper operation, I alternate `/css/themes/velvet.css` to `css/themes/velvet.css`, `/img/grad1.png` to `../../img/grad1.png`.

I don't know if this poses any other risks, but at least now it works properly. Should relative paths be considered instead of absolute paths in repo?

**Comment by Kos-M** [comment]
Hello D-Walter , thanks for feedback ,
I made some test , spinning  some docker containers in latest version of Gogs ( 0.12  ) .

I think is more related to nginx part neither with docker.
In my tests in a normal docker setup , themes are working as they should.And if removed absolute paths and convert them to related , will break existing functionality , wont load css and assets.

Note in docker setup custom dir is actually /data/gogs , so there is no need to create a custom dir in /data/gogs/ .
I will update instructions for docker part.

> Custom directory

> The "custom" directory may not be obvious in Docker environment. The /var/gogs/gogs (in the host) and /data/gogs (in the container) is already the "custom" directory and you do not need to create another layer but directly edit corresponding files under this directory.


Quoted is from docs in[ docker hub](https://hub.docker.com/r/gogs/gogs)

Share if you want you docker setup ( the part describing gogs  container), and reverse proxy nginx config , to see if i can help you with that.

**Comment by D-Walter** [comment]
Thanks for your responding, Kos-M.
After more tests, I recogenized that it may be caused by the sub-path configs in nginx. The url of my gogs is set up as `https://host/gogs/` which leads `/css/themes/velvet.css` points to `https://host/css/themes/velvet.css` by default.
After change absolute path of the static resources the themes work properly.

**Comment by Kos-M** [comment]
Glad you sorted out this :)
